### ISSUE TITLE
More verbose M3Info

### ISSUE THREAD

**Issue by laroque** [project8/monarch#28]
If built in release mode, M3Info run on an egg file prints nothing. I think that there should be some minimal set of information which is always printed when reading the file. Maybe this is the header, maybe this is other stats that M3Info is figuring out, someone else should probably suggest.

I wonder if that should happen as a final print statement outside of the logging system, since it is really the "Info" output for the egg, and not some status log as it runs. (Also, I forget if the logger output goes to STDOUT or STDERR; one could imagine use cases where one wished the logger output were all to STDERR but this 'output' were in STDOUT so that it could be piped elsewhere... I don't think we actually need to support this case but it is maybe worth thinking about).

**Comment by nsoblath** [comment]
Fixed in 3ba12df (released in v3.5.7)
