### ISSUE TITLE
32bit architecture compatibility

### ISSUE THREAD

**Issue by laroque** [project8/monarch#4]
Monarch compiles and "runs" on kaon.physics.ucsb.edu (gentoo 3.3.8 i686) but when MonarchInfo is run on a valid egg, it returns errors that claim that various required fields are not present. The same egg file is read without errors on Myrna (gentoo 3.3.8 x86_64) and various other machines.

**Comment by nsoblath** [comment]
Probably not relevant for Monarch v3, but worth testing to be sure. Will close the issue for now.

**Comment by laroque** [comment]
kaon.physics.ucsb.edu doesn't exist anymore, I'm not sure if we even have any 32 bit machines to test this on. If someone has one and it fails we can open a new issue.
